version: '3'

services:
 node:
   build: .
   environment:
     - NODE_ENV=development
   volumes:
     - ./:/usr/src/app
   command: sh -c 'cd card_attendance_app && npm start'
   ports:
     - '3000:3000'
   tty: true3